# Generated by Django 6.0.6 on 2026-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='cpu_load_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU Load (%)'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='processing_latency_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing Latency (ms)'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='ram_allocation_mb',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM Allocation (MB)'),
        ),
    ]
