# Generated by Django 6.0.6 on 2026-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_healthstatus_cpu_load_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='forecasted_values',
            field=models.JSONField(blank=True, null=True, verbose_name='Forecasted Values'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='predicted_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=10, null=True, verbose_name='Predicted Status'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='prediction_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prediction Generated At'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='prediction_horizon_minutes',
            field=models.FloatField(blank=True, null=True, verbose_name='Prediction Horizon (Minutes)'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='prediction_horizon_steps',
            field=models.IntegerField(default=6, verbose_name='Prediction Horizon (Steps)'),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='predictive_anomaly_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Predictive Anomaly Score'),
        ),
    ]
